# BASE_DEFAULTS are the values erp-workbench needs 
# to find its data

# Variables that can be used in the values
# %(BASE_PATH)s will be replaced with the actual folder where erp-worbench is installed
# %(USER_HOME)s the home folder of the logged in user

BASE_DEFAULTS:
  # erp_version:
  # define what erp version should be uses for a new site
  # this only affects the generation of new site descriptions
  # and can be easily changed in the generated description file.
  erp_version: '11'

  # erp_minor:
  # define what erp minor version should be uses for a new site
  # this only affects the generation of new site descriptions
  # and can be easily changed in the generated site description
  erp_minor: '.0'

  # site_editor:
  # define what editor to use when editing site description
  # this can be any editor like cod, vim, pico ..
  site_editor: 'code'

  # sitesinfo_path:
  # Sites are defined in a sites description file
  # There exist local sites, which are not managed using a source
  # controll system (git), and gloabal sites which are managed with 
  # git and normaly describe sites that eventuall run on a remote server.
  #
  # The sitesinfo_path points to a folder, where these site descriptions 
  # are kept in several subfolders
  # By default it points to a folder within the erp-workbench folder.
  sitesinfo_path: '%(BASE_PATH)s/sites_list/'


  # repo_mapper:
  # repo_mapper allows to use locical names in a site description
  # like:
  # {
  #     'type' : 'git',
  #     'url' : '%(gitlab.redcor.ch)s/afbs/afbs_cms.git',
  # }
  # repo_mapper: 'gitlab.redcor.ch=ssh://git@gitlab.redcor.ch:10022/'

  # sitesinfo_url:
  # sitesinfo_url is the url where the git repository can be found
  # with which the sites are maintained 
  sitesinfo_url: 'localhost'

  # sitesinfo_url:
  # sitesinfo_url is the url where the git repository can be found
  # where the sites are maintained
  # it could be something like: 
  # https://gitlab.redcor.ch/customers/sites_list.git
  # by default it points to localhost, so no sourcecontroll is provided.
  sitesinfo_url: 'localhost'

  # project_path:
  # path to the local projects
  # Here a structure for each erp site is created to build and test a erp/odoo servers
  # using exactly the same setting the live server uses.
  project_path: '%(USER_HOME)s/projects'

  # erp_server_data_path
  # path to server data. Here for every site a set of folders is created
  # that will contain the servers config filestore, log- and dump-files.
  # the folders created are
  # addons:     here the addons of the sites are to be found
  # etc:        here the config files for the site is writen to
  # file_store: here the external files of the file are stored
  # log:        here the logfile of the site is stored
  # dump:       here the a running site can dump its data
  # start-entrypoint.d:
  #             here files to support the starting process of the site can be put
  # by default erp_server_dta_path points to the same folder where erp-workbench resides
  # however if you create many site, this can quickly become confusing
  erp_server_data_path: '%(BASE_PATH)s'

  # docker_dumper_image:
  # erp-workkbench lets you dump a site running in a local/remote docker container
  # into a dump folder within the sites folder structure
  # erp-workbench needs to know what the name of the image is
  # that is used to access and dump a live server
  # to learn more about this, read the dumper description in the erp-workbench help
  docker_dumper_image: 'robertredcor/dumper'

  # local_user_mail:
  # sometimes you want to avoid sending mails to real user
  # when you have copied a life server to your local environment
  # this setting is only used when rederict_emil is installed
  local_user_mail: 'info@company.com'

  # db_user:
  # this is the default data base user, if no db user is defined in the
  # server description file from the sites.yaml file
  db_user: '%(DB_USER)s'

  # db_password:
  # this is the default password, if it not is defined in the
  # server description file from the sites.yaml file
  db_password: 'admin'
