# ROJECT_DEFAULTS how we start a new project

# Variables that can be used in the values
# %(BASE_PATH)s will be replaced with the actual folder where erp-worbnch is installed
# %(USER_HOME)s the home folder of the logged in user

PROJECT_DEFAULTS:
    projectname: undefined
    erp_version: '12'
    erp_minor: '.0'
    flectra_version: '1.1'
    flectra_minor: '.4'
